### ISSUE TITLE
Not an issue - but a question: how often does the octolux server.rb 'refresh' data?

### ISSUE THREAD

**Issue by azimhusain** [celsworth/octolux#1]
Hi there,

This is an amazing script - thank you!

Had a query - for the octolux server.rb - how often is it 'polling' data to output the array on the page from which the magic happens? I'd like to ideally pull this data for other uses but want to understand frequency. 

Is there any way you're aware of to pull data directly from the device, maybe some HTTP post request? or even API? I'd love to be able to grab some of this data in more real time using PHP which I understand better. 

Thanks!

**Comment by celsworth** [comment]
Hi :)

The server doesn't poll for data - it waits for the inverter to send it. As far as I'm aware, there is no way to request the data in realtime :(

The inverter sends SOC % (and a few other things, all of which end up in the JSON output) once every 2 minutes, so that's how often you'll see it update.

**Comment by azimhusain** [comment]
Super useful thanks! Love your work going to see how I can extend it!

I do have an issue with the Octopus script but let me see if I can work it out otherwise I'll raise a issue. Thanks!
