### ISSUE TITLE
More of a question really

### ISSUE THREAD

**Issue by danfulton72** [celsworth/octolux#8]
I'd like to be able to set AC Battery Charge Level so that if my solar forcast is above 15kWh for tomorrow I'd only charge up to 50% overnight (for example).

That setting isn't in registers.rb in lxp-packet, and I've tried network sniffing to figure it out, but haven't been able to!

Can you help!

**Comment by celsworth** [comment]
Hey!

I'm unable to directly test this at the moment as my inverter isn't setup, but I think this may be register 67 - `registers.rb` isn't an exhaustive list but there is a much more complete list in the documentation at https://github.com/celsworth/lxp-packet/blob/master/doc/LXP_REGISTERS.txt#L94 - after a quick skim through, register 67 looks like the most likely one for this.

You can just use 67 directly in place of a constant since it's not defined, so `pkt.set_register(67)`. Give that a try!

**Comment by danfulton72** [comment]
Great, thanks how did I miss the documentation!

Doh

**Comment by celsworth** [comment]
I added that constant pushed `lxp-packet` `0.7.1` in case it helps any :)

**Comment by danfulton72** [comment]
Certainly makes it cleaner!

Thanks

**Comment by danfulton72** [comment]
Worked perfectly with the update to lxp-packet, thanks

**Comment by danfulton72** [comment]
I've updated octolux if you want to accept the changes I'll publish the branch (with permission of course)

**Comment by celsworth** [comment]
Yeah absolutely, open a PR and I'll take a look! Thanks :)

**Comment by chamsters** [comment]
Ignore me - bundle update fixed it :)
